### ISSUE TITLE
Gracefully handle 401 Unauthorized from OAuth userInfo

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/gcb-web-auth#10]
I just tried to accept a delivery with an already-logged-in browser session and received a generic 500 internal server error on the d4s2 web server

It appears that with an expired (or otherwise invalid OAuthToken), the HTTP call to the resource_uri  properly caught. I assumed this would be handled by an auto-refreshing OAuth2Session, but that appears to only refresh tokens when it sees they are expired.

Here, the `/oidc/userinfo` endpoint is returning a 401 unauthorized, which is displayed to the user in web browser as a generic 500 Internal Server Error. 

We should be able to update [get_oauth_token](https://github.com/Duke-GCB/gcb-web-auth/blob/14be312b7dc10d7101b8f97f28f36141e5e673ab/gcb_web_auth/oauth_utils.py#L132) to refresh/retry once if a 401 is encountered.

The following traceback appears in the logs:

```
ERROR:django.request:Internal Server Error: /ownership/
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)
 File "/usr/src/app/ownership/views.py", line 23, in ownership_prompt
   return response_with_delivery(request, request.GET, render_accept_delivery_page)
 File "/usr/src/app/ownership/views.py", line 142, in response_with_delivery
   delivery = details.get_delivery()
 File "/usr/src/app/switchboard/dds_util.py", line 135, in get_delivery
   self.model_populator.update_delivery(self.delivery)
 File "/usr/src/app/switchboard/dds_util.py", line 92, in update_delivery
   project_transfer = self.dds_util.get_project_transfer(delivery.transfer_id)
 File "/usr/src/app/switchboard/dds_util.py", line 49, in get_project_transfer
   return self.remote_store.data_service.get_project_transfer(transfer_id).json()
 File "/usr/src/app/switchboard/dds_util.py", line 19, in remote_store
   dds_token = get_dds_token(self.user)
 File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/oauth_utils.py", line 201, in get_dds_token
   oauth_token = get_oauth_token(user)
 File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/oauth_utils.py", line 142, in get_oauth_token
   raise NoTokenException(e)
NoTokenException: 401 Client Error: Unauthorized for url: https://REMOVED/oidc/userinfo
```

It looks like this token was also presented to DDS but they rejected it too (as expected)

```
ERROR:django.request:Internal Server Error: /api/v1/deliveries/
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
   response = self.process_exception_by_middleware(e, request)
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
   return self.dispatch(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
   response = self.handle_exception(exc)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 454, in dispatch
   self.initial(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 376, in initial
   self.perform_authentication(request)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 310, in perform_authentication
   request.user
 File "/usr/local/lib/python2.7/site-packages/rest_framework/request.py", line 353, in __getattribute__
   return super(Request, self).__getattribute__(attr)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/request.py", line 193, in user
   self._authenticate()
 File "/usr/local/lib/python2.7/site-packages/rest_framework/request.py", line 316, in _authenticate
   user_auth_tuple = authenticator.authenticate(self)
 File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/dukeds_auth.py", line 42, in authenticate
   return self.authenticate_credentials(token)
 File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/dukeds_auth.py", line 48, in authenticate_credentials
   user = self.backend.authenticate(key)
 File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/backends/dukeds.py", line 149, in authenticate
   response = api.get_current_user()
 File "/usr/local/lib/python2.7/site-packages/ddsc/core/ddsapi.py", line 600, in get_current_user
   return self._get_single_item("/current_user", {})
 File "/usr/local/lib/python2.7/site-packages/ddsc/core/ddsapi.py", line 232, in _get_single_item
   return self._check_err(resp, url_suffix, data, allow_pagination=False)
 File "/usr/local/lib/python2.7/site-packages/ddsc/core/ddsapi.py", line 301, in _check_err
   raise DataServiceError(resp, url_suffix, data)
DataServiceError: Error 401 on /current_user Reason:invalid api_token Suggestion:token not properly signed
```

**Comment by dleehr** [comment]
Did some more research on this. #19 was a result of the OAuth service temporarily not accepting refresh tokens. Now that it's working again it seems that the access_tokens obtained by refreshing a token aren't valid.

The auto token refresh is working, and the auto-refreshing OAuth2Session is checking the expires_at date to determine when to refresh the token. But the token received from refreshing is not honored

**Comment by dleehr** [comment]
In other words, I think that the issue is on the OAuth provider side, not our side.

**Comment by dleehr** [comment]
> I think that the issue is on the OAuth provider side, not our side.

Nope, it's here 🤦‍♂️ :

https://github.com/Duke-GCB/gcb-web-auth/blob/4ec2cce21dcdc98d2c8a563d279cd9e7f8835d04/gcb_web_auth/utils.py#L133

The intent here was to revoke the old refresh token before deleting it from our database. But apparently that stops the new token from working too

**Comment by dleehr** [comment]
Making progress - If I manually change the expires_at time in the token, gcb-web-auth will auto-refresh the token and the userinfo call completes successfully.

However, this only works during the 1 hour lifetime of the token because the refresh_token expires. The `refresh_token` returned when refreshing is identical to the original `refresh_token`. The expiration time is encoded into the token (JWT, base64), so it's easy to see the expiration time.

At best, this mechanism can get a second hour of access if the token is refreshed right before the end of the first hour.

Based on other providers, it seems uncommon for refresh tokens to expire. Or if they do, it's a much longer period than an hour. I created a service now ticket.

**Comment by dleehr** [comment]
The provider has changed to give us refresh tokens with no expiration, and I confirmed that a token could be automatically refreshed by gcb-web-auth after 2 hours.

#20 Fixes our implementation so that tokens can be correctly refreshed.
