### ISSUE TITLE
Error in attempting to refresh tokens

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/gcb-web-auth#19]
A job in bespin is failing to complete during the `_give_download_permissions` call.

bespin-api is attempting to refresh the OAuth token, but this call fails with the following:

```
Invoking 0 token response hooks.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/utils.py", line 79, in current_user_details
    return fetch_user_details(oauth_service, session)
  File "/usr/local/lib/python2.7/site-packages/gcb_web_auth/utils.py", line 95, in fetch_user_details
    response = session.post(oauth_service.resource_uri)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 343, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by dleehr** [comment]
Debugging from bespin-web container:

```
$ sudo docker exec -it bespin-web bash
$ wait-for-postgres.sh python manage.py shell

import logging
import sys
from requests_oauthlib import __name__ as rname
log = logging.getLogger(rname)
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler(sys.stdout))

from gcb_web_auth.utils import *
from django.contrib.auth.models import User
service = OAuthService.objects.first()
user = User.objects.get(username='theuser@duke.edu')

current_user_details(service, user)
```

Debug logging shows (token details removed):

```
Prepared refresh token request body grant_type=refresh_token&refresh_token=REMOVED&client_id= REMOVED&client_secret=REMOVED
Requesting url https://oauth.oit.duke.edu/oidc/token using method POST.
Supplying headers {u'Content-Type': u'application/x-www-form-urlencoded;charset=UTF-8', u'Accept': u'application/json'} and data {u'client_secret': u'REMOVED', u'grant_type': u'refresh_token', u'client_id': u'REMOVED', u'refresh_token': u'REMOVED'}
Passing through key word arguments {'verify': True, 'json': None, 'proxies': None, 'auth': None, 'timeout': None}.
Request to refresh token completed with status 401.
Response headers were {'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-store', 'Date': 'Mon, 28 Aug 2017 15:48:47 GMT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json;charset=UTF-8', 'WWW-Authenticate': 'Bearer error="invalid_token", error_description="Invalid refresh token: REMOVED'} and content {"error":"invalid_token","error_description":"Invalid refresh token: REMOVED."}.
Invoking 0 token response hooks.

**Comment by dleehr** [comment]
Though the refresh token is removed, I did try to decode the base64 JWT and it does appear to be truncated.

According to https://jwt.io, there are 3 components: `header.payload.signature`

These tokens have `header.payload.` and the header itself is only a partial dictionary: `{"alg":"none`

Perhaps that's not critical to the implementation, but there's no signature.

**Comment by dleehr** [comment]
Definitely an issue with refreshing the token.

Steps to reproduce inside bespin-api

1. Delete OAuthToken object for a user
2. Login to the web application to cause a new OAuthToken to be created
3. Run above script excerpt that ends with `current_user_details(service, user)` and see that user details are correctly fetched
4. Wait 1 hour for token to expire, causing the OAuth2Session to try to refresh the token
5. Run `current_user_details(service, user)` again and see `MissingTokenError`

**Comment by dleehr** [comment]
Similar to #10. Also fails with https://auth0.com/docs/tokens/refresh-token/current. If posting JSON, the response is `{"error":"invalid_client","error_description":"Bad client credentials"}`, but posting form encoded data, the response is `{"error":"invalid_token","error_description":"Invalid refresh token:...}`

**Comment by dleehr** [comment]
Seems to have been an intermittent bug on token refresh. D4S2 tokens were refreshing just fine but GCB-bespin ones were not. In the last few minutes it started working again and I could refresh GCB-bespin tokens.

Now I'm running into #10 when trying to call `current_user_details(service, user)`

**Comment by dleehr** [comment]
#20 Fixes our implementation so that tokens can be correctly refreshed.

There was also a configuration issue on the provider side. The refresh tokens were set to expire after 1 hour, making them ineffective for offline access. The provider has changed to give us refresh tokens with no expiration, and I confirmed that a token could be automatically refreshed by gcb-web-auth after 2 hours.
